[workspace]
members = [
    #"recz",
    "redt",
    "regr",
    #"remc",
    "renc",
    "resy"
]
resolver = "2"

[workspace.package]
authors = ["Maksim Tomkavich <quendimax@gmail.com>"]
edition = "2024"
repository = "https://github.com/quendimax/re"

[workspace.dependencies]
arrayvec = "0.7.6"
assert_matches = "1"
bump-stack = "0.5"
ordermap = "1"
ntest = "0.9"
num-traits = "0.2"
paste = "1"
pretty_assertions = "1"
prettyplease = "0.2"
proc-macro2 = "1"
proptest = "1"
quote = "1"
regex-syntax = "0.8.5"
smallvec = "1"
static_assertions = "1"
syn = "2"
test-case = "3.3"
thiserror = "2"
