[workspace]
members = [
    "recz",
    "recz-adt",
    "recz-bench",
    "recz-cli",
    "recz-codec",
    "recz-codegen",
    "recz-graph",
    "recz-macro",
    "recz-syntax",
]
default-members = [
    "recz",
    "recz-adt",
    "recz-codec",
    "recz-codegen",
    "recz-graph",
    "recz-macro",
    "recz-syntax",
]
resolver = "3"

[workspace.package]
authors = ["Maksim Tomkavich <quendimax@gmail.com>"]
edition = "2024"
repository = "https://github.com/quendimax/recz"

[workspace.dependencies]
ahash = "0.8"
arrayvec = { version = "0.7", default-features = false }
bumpish = { git = "https://codeberg.org/quendimax/bumpish.git"}
clap = "4.6"
equivalent = { version = "1", default-features = false }
miette = "7"
owo-colors = "4"
paste = "1"
pretty_assertions = "1"
prettyplease = "0.2"
proc-macro2 = "1"
proptest = "1"
quote = "1"
regex-syntax = "0.8.5"
smallvec = "1"
syn = "3"
test-case = "3.3"
thiserror = "2"

[profile.dev]
debug = false

[profile.bench]
debug = true
strip = false
