[package]
name = "recz-graph"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bumpish.workspace = true
recz-adt = { path = "../recz-adt" }
recz-syntax = { path = "../recz-syntax" }

[dev-dependencies]
pretty_assertions.workspace = true
smallvec.workspace = true
