[package]
name = "recz-bench"
version = "0.1.0"
publish = false

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
recz-adt = { path = "../recz-adt" }
recz-graph = { path = "../recz-graph" }
recz-syntax = { path = "../recz-syntax" }

[dev-dependencies]
gungraun = "0.19.4"

[[bench]]
harness = false
name = "recz-bench"
path = "benches/benches.rs"
