[package]
name = "recz-bench"
version = "0.1.0"
publish = false

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
recz-adt = { path = "../recz-adt" }

[dev-dependencies]
gungraun = "0.19.4"

[[bench]]
harness = false
name = "recz-adt"
path = "benches/adt.rs"
