[package]
name = "recz_codec"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
arrayvec.workspace = true
recz_adt = { path = "../recz_adt" }
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
pretty_assertions.workspace = true
regex-syntax.workspace = true
test-case.workspace = true

[features]
test-bruteforce-utf8 = []
