[package]
name = "redt"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bump-stack.workspace = true
num-traits.workspace = true
ordermap.workspace = true
smallvec.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
