[package]
name = "resy"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
redt = { path = "../redt" }
renc = { path = "../renc" }
static_assertions.workspace = true
thiserror.workspace = true

[dev-dependencies]
ntest.workspace = true
pretty_assertions.workspace = true
