[package]
name = "recz-syntax"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
miette = { workspace = true, optional = true }
owo-colors.workspace = true
recz-adt = { path = "../recz-adt" }
recz-codec = { path = "../recz-codec" }
recz-graph = { path = "../recz-graph" }
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[features]
default = []
miette = ["dep:miette"]
