[package]
name = "recz-cli"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
argh = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
owo-colors = { workspace = true, features = ["supports-colors"] }
recz-adt = { path = "../recz-adt" }
recz-graph = { path = "../recz-graph" }
recz-syntax = { path = "../recz-syntax" }
thiserror = { workspace = true }
