[package]
name = "recz-cli"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bat = { workspace = true, features = [] }
clap = { workspace = true, features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
owo-colors = { workspace = true, features = ["supports-colors"] }
prettyplease.workspace = true
quote.workspace = true
recz-adt = { path = "../recz-adt" }
recz-codegen = { path = "../recz-codegen" }
recz-graph = { path = "../recz-graph" }
recz-syntax = { path = "../recz-syntax", features = ["miette"] }
syn = { workspace = true, features = ["parsing"] }
