[package]
name = "recz-cli"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
argh = "0.1.19"
owo-colors.workspace = true
recz-adt = { path = "../recz-adt" }
recz-graph = { path = "../recz-graph" }
recz-syntax = { path = "../recz-syntax" }
supports-color.workspace = true
