[package]
name = "regr"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bump-stack.workspace = true
redt = { path = "../redt" }
resy = { path = "../resy" }
smallvec.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
smallvec.workspace = true
